todo:
  image: myapp
  volumes:
        - "/path/to/your/folder/:/var/www/html"
  links:
    - db:mysql
  ports:
    - 80:80
db:
  image: mysql:5.7
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: symfony
    MYSQL_USER: user
    MYSQL_PASSWORD: user

#docker run -d -p 80:80 --name name_projects -v /path/to/your/folder/:/var/www/html --link mysql:mysql --link postgres:postgres myapp
#docker run -d -p 3306:3306 --name mysql -e MYSQL_ROOT_PASSWORD=mysecretpassword mysql
#docker run -d -p 5432:5432 --name postgres -e POSTGRES_PASSWORD=mysecretpassword postgres