security:
   encoders:
       Package\UserBundle\Entity\User:
           algorithm: bcrypt
           cost: 17

   providers:
       our_db_provider:
           entity:
               class: PackageUserBundle:User
               property: username

   firewalls:
        dev:
            pattern: ^/(_(profiler|wdt) |css|images|js)/
            security: false

        default:
            pattern:    ^/
            anonymous: ~
            form_login:
                  login_path: PackageUserBundle:Security:Login
                  default_target_path: PackageDefaultsBundle:Pages:Index
                  check_path: _check_path
                  username_parameter: login[username]
                  password_parameter: login[password]
            logout:
                path: _logout
                target: /
            remember_me:
                secret:   '%secret%'
                lifetime: 432000 # 5 day in seconds
                path:     /
                remember_me_parameter: login[remember_me]
#        secured_area:
#            form_login:
#                csrf_token_generator: security.csrf.token_manager

   role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

   access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }