common_user_security:
    resource: "@PackageUserBundle/Controller/SecurityController.php"
    type:     annotation
    prefix:   /

common_user_user:
    resource: "@PackageUserBundle/Controller/UserController.php"
    type:     annotation
    prefix:   /

_check_path:
    path: /login-check

_logout:
    path: /logout